name: Ryddig S23
version: "1.0.6"
slug: ryddig_s23
description: Ryddig Sagmesterveien 23

arch:
  - aarch64  

startup: application
boot: auto
init: false

image: ghcr.io/telrun/householdtasks

ingress: true
ingress_port: 8080

panel_icon: mdi:web
panel_title: Ryddig S23

stage: experimental

options:
  google_client_id: ""
  google_client_secret: password

schema:
  google_client_id: str
  google_client_secret: password